// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inventory.proto

package zw_com_shop_srv_inventory

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqUpdateInventory struct {
	GoodsId              uint32   `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	Num                  int64    `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUpdateInventory) Reset()         { *m = ReqUpdateInventory{} }
func (m *ReqUpdateInventory) String() string { return proto.CompactTextString(m) }
func (*ReqUpdateInventory) ProtoMessage()    {}
func (*ReqUpdateInventory) Descriptor() ([]byte, []int) {
	return fileDescriptor_7173caedb7c6ae96, []int{0}
}

func (m *ReqUpdateInventory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUpdateInventory.Unmarshal(m, b)
}
func (m *ReqUpdateInventory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUpdateInventory.Marshal(b, m, deterministic)
}
func (m *ReqUpdateInventory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUpdateInventory.Merge(m, src)
}
func (m *ReqUpdateInventory) XXX_Size() int {
	return xxx_messageInfo_ReqUpdateInventory.Size(m)
}
func (m *ReqUpdateInventory) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUpdateInventory.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUpdateInventory proto.InternalMessageInfo

func (m *ReqUpdateInventory) GetGoodsId() uint32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *ReqUpdateInventory) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type GoodsId struct {
	GoodsId              uint32   `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodsId) Reset()         { *m = GoodsId{} }
func (m *GoodsId) String() string { return proto.CompactTextString(m) }
func (*GoodsId) ProtoMessage()    {}
func (*GoodsId) Descriptor() ([]byte, []int) {
	return fileDescriptor_7173caedb7c6ae96, []int{1}
}

func (m *GoodsId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodsId.Unmarshal(m, b)
}
func (m *GoodsId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodsId.Marshal(b, m, deterministic)
}
func (m *GoodsId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodsId.Merge(m, src)
}
func (m *GoodsId) XXX_Size() int {
	return xxx_messageInfo_GoodsId.Size(m)
}
func (m *GoodsId) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodsId.DiscardUnknown(m)
}

var xxx_messageInfo_GoodsId proto.InternalMessageInfo

func (m *GoodsId) GetGoodsId() uint32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

type InventoryCount struct {
	Count                uint64   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InventoryCount) Reset()         { *m = InventoryCount{} }
func (m *InventoryCount) String() string { return proto.CompactTextString(m) }
func (*InventoryCount) ProtoMessage()    {}
func (*InventoryCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_7173caedb7c6ae96, []int{2}
}

func (m *InventoryCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InventoryCount.Unmarshal(m, b)
}
func (m *InventoryCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InventoryCount.Marshal(b, m, deterministic)
}
func (m *InventoryCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InventoryCount.Merge(m, src)
}
func (m *InventoryCount) XXX_Size() int {
	return xxx_messageInfo_InventoryCount.Size(m)
}
func (m *InventoryCount) XXX_DiscardUnknown() {
	xxx_messageInfo_InventoryCount.DiscardUnknown(m)
}

var xxx_messageInfo_InventoryCount proto.InternalMessageInfo

func (m *InventoryCount) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Ping struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_7173caedb7c6ae96, []int{3}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type Pong struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_7173caedb7c6ae96, []int{4}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

func init() {
	proto.RegisterType((*ReqUpdateInventory)(nil), "zw.com.shop.srv.inventory.ReqUpdateInventory")
	proto.RegisterType((*GoodsId)(nil), "zw.com.shop.srv.inventory.GoodsId")
	proto.RegisterType((*InventoryCount)(nil), "zw.com.shop.srv.inventory.InventoryCount")
	proto.RegisterType((*Ping)(nil), "zw.com.shop.srv.inventory.Ping")
	proto.RegisterType((*Pong)(nil), "zw.com.shop.srv.inventory.Pong")
}

func init() { proto.RegisterFile("inventory.proto", fileDescriptor_7173caedb7c6ae96) }

var fileDescriptor_7173caedb7c6ae96 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0xcc, 0x2b, 0x4b,
	0xcd, 0x2b, 0xc9, 0x2f, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0xac, 0x2a, 0xd7,
	0x4b, 0xce, 0xcf, 0xd5, 0x2b, 0xce, 0xc8, 0x2f, 0xd0, 0x2b, 0x2e, 0x2a, 0xd3, 0x83, 0x2b, 0x50,
	0x72, 0xe4, 0x12, 0x0a, 0x4a, 0x2d, 0x0c, 0x2d, 0x48, 0x49, 0x2c, 0x49, 0xf5, 0x84, 0x89, 0x0a,
	0x49, 0x72, 0x71, 0xa4, 0xe7, 0xe7, 0xa7, 0x14, 0xc7, 0x67, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a,
	0xf0, 0x06, 0xb1, 0x83, 0xf9, 0x9e, 0x29, 0x42, 0x02, 0x5c, 0xcc, 0x79, 0xa5, 0xb9, 0x12, 0x4c,
	0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x20, 0xa6, 0x92, 0x0a, 0x17, 0xbb, 0x3b, 0x54, 0x12, 0xb7, 0x3e,
	0x25, 0x35, 0x2e, 0x3e, 0xb8, 0xf9, 0xce, 0xf9, 0xa5, 0x79, 0x25, 0x42, 0x22, 0x5c, 0xac, 0xc9,
	0x20, 0x06, 0x58, 0x25, 0x4b, 0x10, 0x84, 0xa3, 0x24, 0xc7, 0xc5, 0x12, 0x90, 0x99, 0x97, 0x2e,
	0x24, 0xc6, 0xc5, 0x56, 0x5c, 0x52, 0x94, 0x9f, 0x9d, 0x0a, 0x96, 0x66, 0x0e, 0x82, 0xf2, 0xc0,
	0xf2, 0xf9, 0xb8, 0xe5, 0x8d, 0xd6, 0x33, 0x71, 0x71, 0x22, 0x3c, 0x92, 0xcb, 0xc5, 0x8f, 0xee,
	0x37, 0x5d, 0x3d, 0x9c, 0xa1, 0xa1, 0x87, 0x19, 0x14, 0x52, 0x9a, 0x78, 0x94, 0xa3, 0x7a, 0x48,
	0x89, 0x41, 0x28, 0x9e, 0x8b, 0xc7, 0x3d, 0xb5, 0x04, 0x61, 0x97, 0x12, 0x1e, 0xcd, 0xd0, 0x30,
	0x23, 0xcd, 0x82, 0x20, 0x2e, 0x0e, 0x50, 0xe8, 0x80, 0x43, 0x40, 0x1e, 0x8f, 0x46, 0x90, 0x22,
	0x29, 0xbc, 0x0a, 0xf2, 0xf3, 0xd2, 0x95, 0x18, 0x34, 0x18, 0x0d, 0x18, 0x93, 0xd8, 0xc0, 0x89,
	0xc4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x89, 0x28, 0x6d, 0x37, 0x02, 0x00, 0x00,
}
